# Generated by Django 2.1.1 on 2018-11-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenHouseGases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO2', models.IntegerField()),
                ('SO2', models.IntegerField()),
                ('NOx', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='energysource',
            name='state',
        ),
        migrations.RemoveField(
            model_name='producertype',
            name='state',
        ),
        migrations.AddField(
            model_name='greenhousegases',
            name='energy_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verde.EnergySource'),
        ),
        migrations.AddField(
            model_name='greenhousegases',
            name='producer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verde.ProducerType'),
        ),
        migrations.AddField(
            model_name='greenhousegases',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='verde.State'),
        ),
    ]
